version: '3'

services:
  flask_app:
    build: ./
    container_name: flask_app
    
    volumes:
      - ./flask/:/flask
    restart: always
    # command: bash -c 'cd /flask/api && gunicorn "app:app()" --workers 2  --bind 0.0.0.0:5000 --timeout 30'
    command: bash -c 'cd /flask/ && python app.py'
    ports:
        - "0.0.0.0:5000:5000"
  
  
